---
- name: Update peers
  ansible.builtin.set_fact:
    wireguard_peers: "{{ new_wireguard_peers }}"
  no_log: true

- name: Move wireguard server config
  ansible.builtin.template:
    src: server.conf.j2
    dest: "{{ wireguard_server_config_dir }}/{{ wireguard_iffname }}.conf"
    mode: u=rw,g=,o=
  become: true
  notify: restart wireguard service

- name: Create client wireguard configs
  ansible.builtin.template:
    src: client.conf.j2
    dest: "{{ wireguard_client_config_dir }}/{{ inventory_hostname }}-{{ peer_id }}{% if peer.name %}-{{ peer.name }}{% endif %}.conf"
    mode: u=rw,g=rw,o=
  delegate_to: "{{ wireguard_client_config_storage_host }}"
  notify: restart wireguard service
  loop: "{{ wireguard_peers }}"
  loop_control:
    index_var: peer_id
    loop_var: peer
